import {demo} from "../data/demo.js";
const state={role:"admin",view:"dashboard",selected:null,query:"",filter:"Tous"};
const app=document.querySelector("#app");
const labels={admin:"Mairie",citizen:"Citoyenne",agent:"Agent terrain"};
const navs={
 admin:[["dashboard","⌂","Pilotage"],["reports","◈","Signalements"],["missions","◷","Missions"],["agents","♙","Agents"]],
 citizen:[["dashboard","⌂","Accueil"],["reports","◈","Mes signalements"],["new","＋","Nouveau signalement"],["profile","○","Profil"]],
 agent:[["dashboard","⌂","Terrain"],["missions","◷","Mes missions"],["reports","◈","Historique"],["profile","○","Profil"]]
};
function reports(){let a=demo.reports;if(state.query)a=a.filter(r=>(r.id+" "+r.title+" "+r.area+" "+r.category).toLowerCase().includes(state.query.toLowerCase()));if(state.filter!=="Tous")a=a.filter(r=>r.status===state.filter||r.category===state.filter);return a}
function badge(s){let c=s.includes("Intervention")?"green":s.includes("Inspection")||s==="Qualifié"?"orange":s==="Contre-visite"?"blue":"yellow";return '<span class="badge '+c+'">'+s+"</span>"}
function row(r){return '<button class="report-row" data-report="'+r.id+'"><div class="report-main"><span class="priority '+r.priority.toLowerCase()+'"></span><div><div class="report-title">'+r.id+" · "+r.title+'</div><div class="report-meta">'+r.area+" · "+r.category+" · "+r.date+'</div><div class="progress"><i style="width:'+r.progress+'%"></i></div></div></div><div>'+badge(r.status)+"</div></button>"}
function shell(body){
 const nav=navs[state.role].map(n=>'<button class="'+(state.view===n[0]?"active":"")+'" data-nav="'+n[0]+'"><i class="nav-icon">'+n[1]+"</i><span>"+n[2]+"</span></button>").join("");
 const u=demo.users[state.role], initials=u.name.split(" ").map(x=>x[0]).join("").slice(0,2);
 return '<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">S</div><strong>SunuGox</strong></div><div class="role-switch"><small>ESPACE ACTIF</small><select class="role-select" id="role"><option value="admin" '+(state.role==="admin"?"selected":"")+'>Mairie</option><option value="citizen" '+(state.role==="citizen"?"selected":"")+'>Citoyenne</option><option value="agent" '+(state.role==="agent"?"selected":"")+'>Agent terrain</option></select></div><nav class="nav">'+nav+'</nav><div class="sidebar-foot">SunuGox · Opérations urbaines<br>Prototype fonctionnel · Dakar</div></aside><main class="main"><header class="topbar"><div class="crumb">SunuGox / <b>'+labels[state.role]+"</b></div><div class="top-actions"><button class="icon-btn" id="notify">♢</button><div class="avatar">"+initials+"</div></div></header><section class="content">"+body+"</section></main></div>";
}
function admin(){
 const a=reports();
 return '<div class="hero"><div><div class="eyebrow">Centre opérationnel</div><h1>La ville, dossier par dossier.</h1><p>Suivez les signalements de leur réception jusqu’à la clôture.</p></div><button class="primary" data-nav="reports">Voir les dossiers</button></div><div class="stats"><div class="stat"><span class="label">À qualifier</span><strong>12</strong><span class="delta">+3 aujourd’hui</span></div><div class="stat"><span class="label">Missions actives</span><strong>08</strong><span class="delta">6 agents terrain</span></div><div class="stat"><span class="label">Interventions</span><strong>17</strong><span class="delta">4 à contrôler</span></div><div class="stat"><span class="label">Délai moyen</span><strong>3,2 j</strong><span class="delta">30 derniers jours</span></div></div><div class="grid"><div class="panel"><div class="panel-head"><div><h2>Dossiers à surveiller</h2><span class="muted">Priorité opérationnelle</span></div><button class="filter" data-nav="reports">Tout voir →</button></div><div class="report-list">'+a.map(row).join("")+'</div></div><div class="side-stack">'+activity()+"</div></div>";
}
function activity(){return '<div class="panel"><div class="panel-head"><div><h2>Fil d’activité</h2><span class="muted">Aujourd’hui</span></div></div><div class="activity">'+demo.reports[0].history.slice().reverse().map(h=>'<div class="activity-item"><span class="dot"></span><div><b>'+h[1]+"</b><p>"+h[0]+" · "+h[2]+"</p></div></div>").join("")+"</div></div><div class="panel"><div class="panel-head"><div><h2>Agents terrain</h2><span class="muted">Disponibilité</span></div></div><div class="activity">"+demo.agents.map(a=>'<div class="activity-item"><span class="dot"></span><div><b>'+a.name+"</b><p>"+a.specialty+" · "+a.availability+"</p></div></div>").join("")+"</div></div>"}
function citizen(){let a=demo.reports.filter(r=>r.citizen==="Awa Ndiaye"||r.id==="SG-2048");return '<div class="hero"><div><div class="eyebrow">Mon espace</div><h1>Bonjour Awa.</h1><p>Voici où en sont vos signalements.</p></div><button class="primary" data-nav="new">＋ Nouveau signalement</button></div><div class="stats"><div class="stat"><span class="label">Mes dossiers</span><strong>3</strong><span class="delta">1 en cours</span></div><div class="stat"><span class="label">En traitement</span><strong>2</strong><span class="delta">Suivi actif</span></div><div class="stat"><span class="label">Résolus</span><strong>1</strong><span class="delta">Merci pour votre vigilance</span></div><div class="stat"><span class="label">Zone</span><strong style="font-size:19px">Yeumbeul</strong><span class="delta">Dakar</span></div></div><div class="panel"><div class="panel-head"><div><h2>Mes signalements</h2><span class="muted">Une même histoire, du signalement à la résolution.</span></div></div><div class="report-list">'+a.map(row).join("")+"</div></div>"}
function agent(){let r=demo.reports.filter(x=>x.assignee==="Moussa Diop")[0];return '<div class="hero"><div><div class="eyebrow">Terrain · Aujourd’hui</div><h1>Bonjour Moussa.</h1><p>Votre prochaine mission est prête.</p></div><button class="primary" data-nav="missions">Ouvrir mon agenda</button></div><div class="stats"><div class="stat"><span class="label">Missions du jour</span><strong>2</strong><span class="delta">1 inspection · 1 intervention</span></div><div class="stat"><span class="label">Zone</span><strong style="font-size:19px">Yeumbeul</strong><span class="delta">Voirie</span></div><div class="stat"><span class="label">Rapports à saisir</span><strong>1</strong><span class="delta">Après inspection</span></div><div class="stat"><span class="label">Prochaine mission</span><strong style="font-size:19px">10:30</strong><span class="delta">'+r.id+"</span></div></div><div class="panel"><div class="panel-head"><div><h2>Ma prochaine mission</h2><span class="muted">Priorité élevée</span></div>"+badge(r.status)+"</div><div style="padding:20px"><h2 style="font:700 22px 'Space Grotesk'">"+r.title+"</h2><p class="muted" style="margin-top:6px">"+r.area+" · "+r.category+'</p><div class="map"><div class="pin"></div></div><button class="primary" data-report="'+r.id+'" style="width:100%">Ouvrir la mission</button></div></div>"}
function listPage(){return '<div class="hero"><div><div class="eyebrow">Dossiers</div><h1>'+((state.role==="agent")?"Mes missions":"Tous les signalements")+'</h1><p>Recherchez un dossier et ouvrez son parcours opérationnel.</p></div><button class="primary" data-nav="new">＋ Nouveau signalement</button></div><div class="panel"><div class="panel-head"><div class="filters"><input class="search" id="search" placeholder="Rechercher un dossier…" value="'+state.query+'"><select class="filter" id="filter"><option>Tous</option><option>Inspection terrain</option><option>Intervention en cours</option><option>Contre-visite</option><option>Voirie</option><option>Propreté</option></select></div><span class="muted">'+reports().length+" dossier(s)</span></div><div class="report-list">"+reports().map(row).join("")+"</div></div>"}
function detail(r){let next={"Inspection terrain":"Saisir le rapport d’inspection","Intervention en cours":"Déclarer l’intervention terminée","Contre-visite":"Confirmer la contre-visite","Qualifié":"Affecter une mission"}[r.status]||"Faire avancer le dossier";return '<div class="detail"><button class="back" data-nav="reports">← Retour aux dossiers</button><div class="detail-head"><div><div class="eyebrow">'+r.id+" · "+r.category+"</div><h1>"+r.title+"</h1><p class="muted" style="margin-top:7px">"+r.area+" · Signalé le "+r.date+" · "+r.citizen+'</p></div><div>'+badge(r.status)+"</div></div><div class="detail-grid"><div class="panel"><div class="panel-head"><div><h2>Parcours du dossier</h2><span class="muted">Responsabilités et décisions</span></div><span class="badge orange">"+r.progress+"% du parcours</span></div><div class="timeline">"+r.history.map(h=>'<div class="timeline-item"><span class="timeline-time">'+h[0]+'</span><span class="timeline-line"></span><div><div class="timeline-title">'+h[1]+'</div><div class="timeline-by">Responsable · '+h[2]+"</div></div></div>").join("")+'</div></div><div class="side-stack"><div class="panel"><div class="panel-head"><div><h2>Localisation</h2><span class="muted">'+r.area+'</span></div></div><div class="map"><div class="pin"></div></div><div style="padding:0 18px 18px;font-size:12px;color:var(--muted)">Coordonnées : '+r.coordinates+'</div></div><div class="panel"><div class="panel-head"><div><h2>Prochaine action</h2><span class="muted">À traiter</span></div></div><div style="padding:20px"><b>'+next+'</b><p class="muted" style="margin-top:6px">Responsable · '+r.assignee+'</p><button class="primary" id="advance" style="margin-top:15px;width:100%">Valider l’étape</button></div></div></div></div><div class="panel"><div class="panel-head"><div><h2>Description</h2><span class="muted">Constat citoyen</span></div></div><div style="padding:20px;line-height:1.7;font-size:14px">'+r.description+"</div></div></div>"}
function form(){return '<div class="hero"><div><div class="eyebrow">Citoyenne</div><h1>Signaler un problème</h1><p>Quelques informations suffisent. La mairie prendra ensuite le relais.</p></div></div><div class="panel"><form class="form" id="report-form"><div class="field"><label>Titre du problème</label><input required value="Nid-de-poule important sur la route de Yeumbeul"></div><div class="field"><label>Catégorie</label><select><option>Voirie</option><option>Éclairage</option><option>Propreté</option><option>Assainissement</option></select></div><div class="field"><label>Localisation</label><input required value="Yeumbeul Nord, Dakar"></div><div class="field"><label>Description</label><textarea required>Déformation importante de la chaussée qui oblige les véhicules à ralentir et contourner la zone.</textarea></div><div class="field"><label>Photo</label><input type="file" accept="image/*"></div><button class="primary">Envoyer le signalement</button></form></div>"}
function agents(){return '<div class="hero"><div><div class="eyebrow">Ressources terrain</div><h1>Agents</h1><p>Disponibilité, spécialité et charge opérationnelle.</p></div></div><div class="panel"><div class="report-list">'+demo.agents.map(a=>'<div class="report-row"><div><div class="report-title">'+a.name+'</div><div class="report-meta">'+a.specialty+" · "+a.missions+" missions</div></div>"+badge(a.availability)+"</div>").join("")+"</div></div>"}
function toast(m){let e=document.createElement("div");e.className="toast";e.textContent=m;document.querySelector("#toast-root").append(e);setTimeout(()=>e.remove(),2800)}
function render(){let body=state.selected?detail(state.selected):state.view==="new"?form():state.view==="agents"?agents():state.view==="reports"||state.view==="missions"?listPage():state.role==="citizen"?citizen():state.role==="agent"?agent():admin();app.innerHTML=shell(body);bind()}
function bind(){
 document.querySelector("#role")?.addEventListener("change",e=>{state.role=e.target.value;state.view="dashboard";state.selected=null;render();toast("Espace changé · données synchronisées")});
 document.querySelectorAll("[data-nav]").forEach(e=>e.addEventListener("click",()=>{state.view=e.dataset.nav;state.selected=null;render()}));
 document.querySelectorAll("[data-report]").forEach(e=>e.addEventListener("click",()=>{state.selected=demo.reports.find(r=>r.id===e.dataset.report);render()}));
 document.querySelector("#search")?.addEventListener("input",e=>{state.query=e.target.value;render();document.querySelector("#search")?.focus()});
 document.querySelector("#filter")?.addEventListener("change",e=>{state.filter=e.target.value;render()});
 document.querySelector("#notify")?.addEventListener("click",()=>toast("3 informations nouvelles · SG-2048 a été affecté"));
 document.querySelector("#report-form")?.addEventListener("submit",e=>{e.preventDefault();toast("Signalement enregistré · SG-2052");state.view="reports";render()});
 document.querySelector("#advance")?.addEventListener("click",()=>toast("Étape validée · historique mis à jour"));
}
render();